MODEL:
  NAME: 'resnet50'
  DEVICE: 'cuda'
  CLASSES: 1000
  PRETRAINED: 'False'

DATA_DIR: 'dataset'

DATASET:
  IMAGESIZE: 224
  NAME: 'imagenet'

SOLVER:
  OPTIMIZER_NAME: 'Lookaround'
  MAX_EPOCHS: 90
  SCHEDULER_MVALUE: [30, 60]
  LR: 0.1
  BATCH_SIZE: 256
  SCHEDULER_GAMMA: 0.1

  SCHEDULER: 'MultiStepLR'

BUILD_TRANSFORM_NUM: 3
OUTPUT_DIR: 'output/'

